version: "3.7"

networks:

  internal:
    external: false
    name: myapp-internal

  external:
    external: true
    name: external

services:

  myapp-mysql:
    container_name: myapp-mysql
    environment:
      MYSQL_DATABASE: myapp
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    image: mysql:${MYSQL_VERSION:-5.7}
    networks:
      - internal
      - external
    ports:
      - 3306:3306
    tty: true
    volumes:
      - myapp-mysql:/var/lib/mysql

  myapp-redis:
    container_name: myapp-redis
    image: redis:${REDIS_VERSION:-5.0.5-alpine3.10}
    networks:
      - internal
      - external
    ports:
      - 6379:6379
    tty: true
    volumes:
      - myapp-redis:/data

  myapp-php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: myapp-php
    image: myapp-php
    networks:
      - internal
    tty: true
    volumes:
      - ./src:/var/www/html

  myapp-nginx:
    build:
      args:
        NGINX_VERSION: ${NGINX_VERSION:-1.17}
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: myapp-nginx
    image: myapp-nginx
    networks:
      - internal
      - external
    ports:
      - 80:80
    tty: true
    volumes:
      - ./src/public:/var/www/html/public

volumes:
  myapp-mysql:
    name: myapp-mysql
  myapp-redis:
    name: myapp-redis