version: "3.7"

networks:

  internal:
    external: false
    name: ${COMPOSE_PROJECT_NAME}-internal

  external:
    external: true
    name: external

services:

  mysql:
    command: --default-authentication-plugin=mysql_native_password
    container_name: ${COMPOSE_PROJECT_NAME}-mysql
    environment:
      MYSQL_DATABASE: ${COMPOSE_PROJECT_NAME}_local
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    image: mysql:${MYSQL_VERSION:-8.0}
    networks:
      - internal
      - external
    ports:
      - ${MYSQL_EXTERNAL_PORT:-3306}:3306
    tty: true
    volumes:
      - mysql:/var/lib/mysql

  redis:
    container_name: ${COMPOSE_PROJECT_NAME}-redis
    image: redis:${REDIS_VERSION:-5.0-alpine3.11}
    networks:
      - internal
      - external
    ports:
      - ${REDIS_EXTERNAL_PORT:-6379}:6379
    tty: true
    volumes:
      - redis:/data

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME}-php
    depends_on:
      - mysql
      - redis
    image: ${COMPOSE_PROJECT_NAME}-php
    networks:
      - internal
    tty: true
    volumes:
      - ./src:/var/www/html

  nginx:
    build:
      args:
        NGINX_VERSION: ${NGINX_VERSION:-1.17}
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    depends_on:
      - mysql
      - redis
      - php
    image: ${COMPOSE_PROJECT_NAME}-nginx
    networks:
      - internal
      - external
    ports:
      - ${NGINX_EXTERNAL_PORT:-80}:80
    tty: true
    volumes:
      - ./src/public:/var/www/html/public

volumes:
  mysql:
    name: ${COMPOSE_PROJECT_NAME}-mysql
  redis:
    name: ${COMPOSE_PROJECT_NAME}-redis